/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 15 Pro Max Black
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useThree } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  const groupRef = useRef(null);
  let camera = useThree((state) => state.camera);
  let scene = useThree((state) => state.scene);
  

  useLayoutEffect(() => {

    // change model color
    for (let key in materials) {
      if (materials[key].color && key !== "EuTsEfyoAnyJIih") {
        materials[key].color.set("#1e1f20");
      }
    }

    // animation using gsap
    let tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#iphone-model",
        start: "top+=200 top",
        endTrigger: "#separator",
        end: "top top",
        scrub: true,
      },
    });

    tl.fromTo(camera.position, { x: -0.4, y: 1 }, { y: 0 })
      .to(scene.rotation, { y: 0.8 })
      .to(scene.rotation, { y: 1.2 })
      .to(scene.rotation, { y: 1.6 })
      .to(scene.rotation, { y: 2 })
      .to(scene.rotation, { y: 2.4 })
      .to(scene.rotation, { y: 2.8 })
      .to(scene.rotation, { y: 3.2 })
      .to(scene.rotation, { y: 3.6 })
      .to(scene.rotation, { y: 4 })
      .to(scene.rotation, { y: 4.4 })
      .to(scene.rotation, { y: 4.8 })
      .to(scene.rotation, { y: 5.2 })
      .to(scene.rotation, { y: 5.6, z: 0.9 })
      .to(scene.rotation, { y: 6.2, z: 1.1 })
      .to(scene.rotation, { y: 6.4, z: 1.3 })
      .to(camera.position, { x: 0, y: 0, z: 4 })
      .to(scene.rotation, { y: 4.4, z: 0.9 })
      .to(scene.rotation, { y: 3.4, z: 0.5 })
      .to(scene.rotation, { y: 1.4, z: 0.1 })
      .to(scene.rotation, { y: 0, z: 0 });

    return () => {
      tl.kill();
    };
  }, [camera.position,materials,scene.rotation]);
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.ttmRoLdJipiIOmf.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.DjsDkGiopeiEJZK.geometry}
          material={materials.iCxrnlRvbVOguYp}
        />
        <mesh
          geometry={nodes.zraMDXCGczVnffU.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.buRWvyqhBBgcJFo.geometry}
          material={materials.eHgELfGhsUorIYR}
        />
        <mesh
          geometry={nodes.MrMmlCAsAxJpYqQ_0.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.KVYuugCtKRpLNRG_0.geometry}
          material={materials.mvjnAONQuIshyfX}
        />
        <mesh
          geometry={nodes.wqbHSzWaUxBCwxY_0.geometry}
          material={materials.MHFGNLrDQbTNima}
        />
        <mesh
          geometry={nodes.QvGDcbDApaGssma.geometry}
          material={materials.kUhjpatHUvkBwfM}
        />
        <mesh
          geometry={nodes.MGPAkjCLsByKXcN.geometry}
          material={materials.kUhjpatHUvkBwfM}
        />
        <mesh
          geometry={nodes.vFwJFNASGvEHWhs.geometry}
          material={materials.RJoymvEsaIItifI}
        />
        <mesh
          geometry={nodes.fjHkOQLEMoyeYKr.geometry}
          material={materials.AhrzSsKcKjghXhP}
        />
        <mesh
          geometry={nodes.RvfXLdAOBoQdZkP.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.VTXyqxbrBeQSTEt.geometry}
          material={materials.eHgELfGhsUorIYR}
        />
        <mesh
          geometry={nodes.evAxFwhaQUwXuua.geometry}
          material={materials.KSIxMqttXxxmOYl}
        />
        <mesh
          geometry={nodes.USxQiqZgxHbRvqB.geometry}
          material={materials.mcPrzcBUcdqUybC}
        />
        <mesh
          geometry={nodes.TvgBVmqNmSrFVfW.geometry}
          material={materials.pIhYLPqiSQOZTjn}
        />
        <mesh
          geometry={nodes.xJhdvBbfHMKCBPl.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.eYSJBzbqIfsHPsw.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.KbMHiTYyrBmkZwz.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.sVqcZvpZKhwSmoN.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.GuYJryuYunhpphO.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.DOjZomXdJsbbvcr.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.cnreaSmJRdAuFia.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.HKHhmqmAZAOaaKY.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.IZQgEjTfhbNtjHR.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.pvdHknDTGDzVpwc.geometry}
          material={materials.xdyiJLYTYRfJffH}
        />
        <mesh
          geometry={nodes.CfghdUoyzvwzIum.geometry}
          material={materials.jpGaQNgTtEGkTfo}
        />
        <mesh
          geometry={nodes.MHfUXxLdYldKhVJ_0.geometry}
          material={materials.dxCVrUCvYhjVxqy}
        />
        <mesh
          geometry={nodes.TxLQyfBdakwBPHu_0.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.DjdhycfQYjKMDyn.geometry}
          material={materials.ujsvqBWRMnqdwPx}
        />
        <mesh
          geometry={nodes.usFLmqcyrnltBUr.geometry}
          material={materials.sxNzrmuTqVeaXdg}
        />
        <mesh
          geometry={nodes.xXDHkMplTIDAXLN.geometry}
          material={materials.pIJKfZsazmcpEiU}
        />
        <mesh
          geometry={nodes.IZbjANwSMLfgcvD.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.SysBlPspVQNIcce.geometry}
          material={materials.ujsvqBWRMnqdwPx}
        />
        <mesh
          geometry={nodes.vELORlCJixqPHsZ.geometry}
          material={materials.zFdeDaGNRwzccye}
        />
        <mesh
          geometry={nodes.IMPDFDiRXhPIUMV.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.EbQGKrWAqhBHiMv.geometry}
          material={materials.TBLSREBUyLMVtJa}
        />
        <mesh
          geometry={nodes.EddVrWkqZTlvmci.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.aGrbyjnzqoVJenz.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.KSWlaxBcnPDpFCs.geometry}
          material={materials.yQQySPTfbEJufve}
        />
        <mesh
          geometry={nodes.AQkWXGdRSkSZMav.geometry}
          material={materials.ujsvqBWRMnqdwPx}
        />
        <mesh
          geometry={nodes.TakBsdEjEytCAMK.geometry}
          material={materials.ZQfGMLaFcpPaLMU}
        />
        <mesh
          geometry={nodes.IykfmVvLplTsTEW.geometry}
          material={materials.dwrMminMXjXXeek}
        />
        <mesh
          geometry={nodes.wLfSXtbwRlBrwof.geometry}
          material={materials.oZRkkORNzkufnGD}
        />
        <mesh
          geometry={nodes.WJwwVjsahIXbJpU.geometry}
          material={materials.yhcAXNGcJWCqtIS}
        />
        <mesh
          geometry={nodes.cibcwsZWGgGfpme.geometry}
          material={materials.ZQfGMLaFcpPaLMU}
        />
        <mesh
          geometry={nodes.YfrJNXgMvGOAfzz.geometry}
          material={materials.bCgzXjHOanGdTFV}
        />
        <mesh
          geometry={nodes.DCLCbjzqejuvsqH.geometry}
          material={materials.vhaEJjZoqGtyLdo}
        />
        <mesh
          geometry={nodes.dkQXkqysxzfHFiP.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.FscwyiLIVNWUuKe.geometry}
          material={materials.fkUApOHLQsMUdfd}
        />
        <mesh
          geometry={nodes.CdalkzDVnwgdEhS.geometry}
          material={materials.jlzuBkUzuJqgiAK}
        />
        <mesh
          geometry={nodes.NtjcIgolNGgYlCg.geometry}
          material={materials.PpwUTnTFZJXxCoE}
        />
        <mesh
          geometry={nodes.zOPceDOPdLNSscX.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.bxjlJpbNESedyat.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.ehFpgEdYijLjwka.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.IXWuqsIeTqBFLIy.geometry}
          material={materials.EuTsEfyoAnyJIih}
        />
        <mesh
          geometry={nodes.qlwPlhojsxIgqwa.geometry}
          material={materials.EszxgwYUTxbhBrC}
        />
        <mesh
          geometry={nodes.bpqFtgUKAOOPYpk.geometry}
          material={materials.yQQySPTfbEJufve}
        />
        <mesh
          geometry={nodes.dxVZiHfQBLkPYHO.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.guvLdFXlBjMoNra.geometry}
          material={materials.fkUApOHLQsMUdfd}
        />
        <mesh
          geometry={nodes.PRPzbUhYhabBDYt.geometry}
          material={materials.jlzuBkUzuJqgiAK}
        />
        <mesh
          geometry={nodes.oOTDgAlTGbFYzBo.geometry}
          material={materials.PpwUTnTFZJXxCoE}
        />
        <mesh
          geometry={nodes.hGKQDeRmDnGNdjb.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.XRoKUoMkItkzNYL.geometry}
          material={materials.jlzuBkUzuJqgiAK}
        />
        <mesh
          geometry={nodes.FjtgRCsnzEoHpCy.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.gJeeYWdxrKsnsVD.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.KOgQmlOdVEyKocf.geometry}
          material={materials.jlzuBkUzuJqgiAK}
        />
        <mesh
          geometry={nodes.gTmqYtKthFeRVJL.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.obVkazjvaXyXFtA.geometry}
          material={materials.EuTsEfyoAnyJIih}
        />
        <mesh
          geometry={nodes.zFlMfSCaOdRDBFx.geometry}
          material={materials.EszxgwYUTxbhBrC}
        />
        <mesh
          geometry={nodes.ooeiSEXgcJckXsp.geometry}
          material={materials.yQQySPTfbEJufve}
        />
        <mesh
          geometry={nodes.lfXEACUihtLFGfq.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.eWbcqPskBBXuZDe.geometry}
          material={materials.fkUApOHLQsMUdfd}
        />
        <mesh
          geometry={nodes.AdjkxvMXIDEHBMM.geometry}
          material={materials.eShKpuMNVJTRrgg}
        />
        <mesh
          geometry={nodes.drpRvcOgsocXGbn.geometry}
          material={materials.PpwUTnTFZJXxCoE}
        />
        <mesh
          geometry={nodes.KXVnYLSfTdVnSOf.geometry}
          material={materials.jlzuBkUzuJqgiAK}
        />
        <mesh
          geometry={nodes.FFAjDZTPwYrUKAV.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.AwsQCWysocWlYzN.geometry}
          material={materials.xNrofRCqOXXHVZt}
        />
        <mesh
          geometry={nodes.wJqHahKxdxecSAC.geometry}
          material={materials.EuTsEfyoAnyJIih}
        />
        <mesh
          geometry={nodes.SRYqzKwamLGuEGm.geometry}
          material={materials.EszxgwYUTxbhBrC}
        />
        <mesh
          geometry={nodes.yxqQUnbopbiRvZr.geometry}
          material={materials.yQQySPTfbEJufve}
        />
        <mesh
          geometry={nodes.xtMgDHhPqFLAHyB.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.nnqwwoLVdMJlHIF.geometry}
          material={materials.fkUApOHLQsMUdfd}
        />
        <mesh
          geometry={nodes.pXBNoLiaMwsDHRF.geometry}
          material={materials.yiDkEwDSyEhavuP}
        />
        <mesh
          geometry={nodes.SCoTCDlNLPQMMyt.geometry}
          material={materials.yiDkEwDSyEhavuP}
        />
        <mesh
          geometry={nodes.fdZyCEcqJDKBWVW.geometry}
          material={materials.hUlRcbieVuIiOXG}
        />
        <mesh
          geometry={nodes.IkoiNqATMVoZFKD.geometry}
          material={materials.hiVunnLeAHkwGEo}
        />
        <mesh
          geometry={nodes.rqgRAGHOwnuBypi.geometry}
          material={materials.HGhEhpqSBZRnjHC}
        />
        <mesh
          geometry={nodes.npMJxzurVJQlumk.geometry}
          material={materials.JJvGZqtXqnnFakR}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
